service: layer-test

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  profile: daniel

plugins:
  - serverless-jetpack

functions:
  myFunction:
    name: 'myFunction'
    handler: main.handler
    package:
      include:
        - 'main.js'
        - '!node_modules'
    layers:
      - !Ref NodeModulesLambdaLayer

layers:
  NodeModules:
    jetpack:
      roots:
        - ./nodejs
    include:
      - node_modules

package:
  individually: true
  
custom:
  jetpack:
    preInclude:
      - '!**'